name: 🐞 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please provide as much detail as possible.
  - type: checkboxes
    id: prior-search
    attributes:
      label: Have you searched for existing issues?
      description: Please check if this issue has already been reported
      options:
        - label: I have searched existing issues
          required: true
  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: A clear, concise title for the bug
      placeholder: "e.g., App crashes when clicking the save button"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: A clear description of what you were doing and what went wrong
      placeholder: |
        I was trying to...
        I expected to see...
        Instead, I saw...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps we can follow to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. Observe...
    validations:
      required: true
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: What version of the software are you using?
      placeholder: "1.0.0"
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      placeholder: "Paste error output here"
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug?
      options:
        - label: "🔴 Critical - App is unusable"
        - label: "🟠 High - Major feature broken"
        - label: "🟡 Medium - Some features affected"
        - label: "🟢 Low - Minor issue"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Screenshots, videos, or other details..."
    validations:
      required: false
