# PR automation workflow template
# Runs on pull request events for labeling, checks, and comments
# Customize: label rules, required checks, and comment templates
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  label:
    name: Auto-label
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    steps:
      - uses: actions/checkout@v4

      # TODO: Uncomment and configure auto-labeling
      # - uses: actions/labeler@v5
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     # Configure labels in .github/labeler.yml

      - name: Label PR
        uses: actions/github-script@v7
        with:
          script: |
            // Example: label based on file paths
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const labels = [];
            const paths = files.map(f => f.filename);

            if (paths.some(p => p.startsWith('docs/'))) labels.push('documentation');
            if (paths.some(p => p.match(/\.(test|spec)\./))) labels.push('tests');
            // TODO: Add more labeling rules

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels,
              });
            }

  size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const totalChanges = pr.additions + pr.deletions;
            let label = 'size/S';
            if (totalChanges > 500) label = 'size/XL';
            else if (totalChanges > 200) label = 'size/L';
            else if (totalChanges > 50) label = 'size/M';

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label],
            });
